---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/opendatahub-operator.openshift-operators: ""
  name: opendatahub-operator
  namespace: openshift-operators
spec:
  channel: rolling
  installPlanApproval: Automatic
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: opendatahub-operator.v1.10.0
  ---
  # Source: clustergroup/templates/core/subscriptions.yaml
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: opendatahub-operator
#   namespace: openshift-operators
# spec:
#   name: opendatahub-operator
#   source: community-operators
#   sourceNamespace: openshift-marketplace
#   installPlanApproval: Automatic